# Generated by Django 5.0.6 on 2024-06-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="surname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
