# Generated by Django 5.0.6 on 2024-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0002_table_surname_alter_table_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="cellphone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="table",
            name="lastname",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="table",
            name="office",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="table",
            name="photo",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="table",
            name="position",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="table",
            name="status",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="table",
            name="work_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="table",
            name="surname",
            field=models.CharField(default="", max_length=30),
        ),
    ]
