# Generated by Django 5.0.6 on 2024-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0003_table_cellphone_table_lastname_table_office_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
