# Generated by Django 5.0.6 on 2024-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0004_alter_table_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=15)),
                ("surname", models.CharField(default="", max_length=30)),
                ("lastname", models.CharField(default="", max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[(0, "female"), (1, "male")], max_length=1
                    ),
                ),
                ("status", models.CharField(default="", max_length=40)),
                ("office", models.CharField(default="", max_length=20)),
                ("work_phone", models.CharField(default="", max_length=15)),
                ("cellphone", models.CharField(default="", max_length=15)),
                ("position", models.CharField(default="", max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
