# Generated by Django 5.0.6 on 2024-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0005_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="blob_photo",
            field=models.BinaryField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("0", "female"), ("1", "male")], max_length=1
            ),
        ),
    ]
