# Generated by Django 5.0.6 on 2024-06-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTP", "0007_alter_customer_blob_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="blob_photo",
            field=models.BinaryField(default=None),
        ),
    ]
